#!/bin/zsh
(
    while inotifywait -e modify index.haml > /dev/null 2>&1; do
        echo "index.haml -> index.html... \c"
        haml -f html5 index.haml index.html
        echo 'OK'
    done
) &
(
    while inotifywait -e modify css.sass > /dev/null 2>&1; do
        echo "css.sass -> css.css... \c"
        sass css.sass css.css
        echo 'OK'
    done
) &
(
    while inotifywait -e modify js.coffee > /dev/null 2>&1; do
        echo "js.coffee -> js.js... \c"
        coffee -c js.coffee
        echo 'OK'
    done
)

